set(EIGEN_EXTRA_ARGS
  
)

ExternalProject_Add(external_eigen
  URL file://${PACKAGE_DIR}/${EIGEN_FILE}
  DOWNLOAD_DIR ${DOWNLOAD_DIR}
  URL_HASH ${EIGEN_HASH_TYPE}=${EIGEN_HASH}
  PREFIX ${BUILD_DIR}/eigen
  CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${LIBDIR}/eigen ${DEFAULT_CMAKE_FLAGS} ${IMATH_EXTRA_ARGS}
  INSTALL_DIR ${LIBDIR}/eigen
)
