set(EMBREE_BUILD_TYPE)

if(BUILD_STATIC)
  set(EMBREE_BUILD_TYPE
    -DEMBREE_STATIC_LIB=ON    
  )
  
else()
  set(EMBREE_BUILD_TYPE
    -DEMBREE_STATIC_LIB=OFF
  )

endif()
set(EMBREE_EXTRA_ARGS
  ${EMBREE_BUILD_TYPE}
  -DEMBREE_ISPC_SUPPORT=OFF
  -DEMBREE_TUTORIALS=OFF
  -DEMBREE_RAY_MASK=ON
  -DEMBREE_FILTER_FUNCTION=ON
  -DEMBREE_BACKFACE_CULLING=OFF
  -DEMBREE_TASKING_SYSTEM=TBB
  -DEMBREE_TBB_ROOT=${LIBDIR}/tbb
  -DTBB_ROOT=${LIBDIR}/tbb
)

ExternalProject_Add(external_embree
  URL file://${PACKAGE_DIR}/${EMBREE_FILE}
  DOWNLOAD_DIR ${DOWNLOAD_DIR}
  URL_HASH ${EMBREE_HASH_TYPE}=${EMBREE_HASH}
  PREFIX ${BUILD_DIR}/embree
  CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${LIBDIR}/embree ${DEFAULT_CMAKE_FLAGS} ${EMBREE_EXTRA_ARGS}
  INSTALL_DIR ${LIBDIR}/embree
)

add_dependencies(
  external_embree
  external_tbb
)

unset(EMBREE_BUILD_TYPE)
