set(JPEG_EXTRA_ARGS
  -DWITH_JPEG8=ON
  -DENABLE_STATIC=ON
  -DENABLE_SHARED=OFF
  -DCMAKE_INSTALL_LIBDIR=${LIBDIR}/jpeg/lib)

ExternalProject_Add(external_jpeg
  URL file://${PACKAGE_DIR}/${JPEG_FILE}
  DOWNLOAD_DIR ${DOWNLOAD_DIR}
  URL_HASH ${JPEG_HASH_TYPE}=${JPEG_HASH}
  PREFIX ${BUILD_DIR}/jpeg
  CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${LIBDIR}/jpeg ${DEFAULT_CMAKE_FLAGS} ${JPEG_EXTRA_ARGS}
  INSTALL_DIR ${LIBDIR}/jpeg
)

set(JPEG_LIBRARY libjpeg.a)

