set(OPENEXR_EXTRA_ARGS
  -DZLIB_LIBRARY=${LIBDIR}/zlib/lib/libz.a
  -DZLIB_INCLUDE_DIR=${LIBDIR}/zlib/include/
  -DBUILD_TESTING=OFF
  -DOPENEXR_BUILD_BOTH_STATIC_SHARED=OFF
  -DBUILD_SHARED_LIBS=OFF
  -DOPENEXR_INSTALL_TOOLS=OFF
  -DOPENEXR_INSTALL_EXAMPLES=OFF
  -DOPENEXR_LIB_SUFFIX=
  -DOPENEXR_STATIC_LIB_SUFFIX=
  -DImath_DIR=${LIBDIR}/imath/lib/cmake/Imath
)

ExternalProject_Add(external_openexr
  URL file://${PACKAGE_DIR}/${OPENEXR_FILE}
  DOWNLOAD_DIR ${DOWNLOAD_DIR}
  URL_HASH ${OPENEXR_HASH_TYPE}=${OPENEXR_HASH}
  CMAKE_GENERATOR ${PLATFORM_ALT_GENERATOR}
  PREFIX ${BUILD_DIR}/openexr
  CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${LIBDIR}/openexr ${DEFAULT_CMAKE_FLAGS} ${OPENEXR_EXTRA_ARGS}
  INSTALL_DIR ${LIBDIR}/openexr
)

add_dependencies(
  external_openexr
  external_zlib
  external_imath
)
